data:
  dataset: msn_easy
  num_points: 9600
  kwargs:
    canonical_view: false
    target_reduced: 1
model:
  base: srt
  encoder_kwargs:
    max_pooling: false
    pos_start_octave: -5
    num_conv_blocks: 3
    num_att_blocks: 5
  decoder: lightfield
  decoder_kwargs:
    pos_start_octave: -5
    out_dims: 3
  lr_config: step
  lr: 0.0001
  lr_warmup: 2500
training:
  num_workers: 6
  batch_size: 64
  model_selection_metric: psnr
  model_selection_mode: max
  print_every: 100
  visualize_every: 5000
  validate_every: 5000
  checkpoint_every: 1000
  backup_every: 100000
  max_it: 500000
  decay_it: 500000
  lr_warmup: 2500
